version: "3.8"
services:
  # frontend:
  #   image: nginx:1.21.5-alpine
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./frontend/:/usr/share/nginx/html
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    tty: true
    ports:
      - 8000:8000
    volumes:
      - ./backend/app:/go/src/github/guranytou/todo